### ISSUE TITLE
Hardcoded date in getElapsedDate()

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-elasticsearch-backend-listener#1]
Hello,
First thanks for this interesting plugin.

I noticed in getElapsedDate() this:
`            String sElapsed = String.format("2017-01-01 %02d:%02d:%02d", 
                    cal.get(Calendar.HOUR_OF_DAY), 
                    cal.get(Calendar.MINUTE),
                    cal.get(Calendar.SECOND));`

Is it regular that 2017-01-01 is hard coded ?
Why not use the day of load test ?
Thanks

**Comment by delirius325** [comment]
Ahh yes, we'd have to find another way to go about this, but technically this is to be able to compare two Jenkins build in one visualization in Kibana. We could indeed use the current day for ElapsedDate which would make more sense. 

I would create another variable that would go by the name of "ElapsedDateBuild" or something like that.

_To put a certain context, we're automatically executing tests via Jenkins pipelines, although, they are not executed on the same day, but I want to be able to compare the last two build. Therefore, the way that I was able to work around that was by hard-coding a generic date for all sample results._
