### ISSUE TITLE
Publish plugin artifact to Maven Repository

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-elasticsearch-backend-listener#10]
Hello,
I think it would be nice if your plugin could be available on Maven repository as JP plugins.
In the current movement of Shift Left, load testing is integrating the project cycle much earlier. Maven is a popular build system and there is a jmeter-maven-plugin for jmeter that is rather popular based on its statistics for that.

Having your plugin available in maven like many of jmeter-plugins plugin might be interesting for project that use ELK and that want to integrate it in their build lifecycle.

Regards
Philippe M.

**Comment by delirius325** [comment]
Very good point, I'll make sure to publish the plugin to Maven. Thanks for the suggestion!

**Comment by delirius325** [comment]
Plugin published to Maven Central.

```xml
<dependency>
  <groupId>io.github.delirius325</groupId>
  <artifactId>jmeter.backendlistener.elasticsearch</artifactId>
  <version>2.2.2</version>
</dependency>
```
