### ISSUE TITLE
Fatjar jmeter.backendlistener.elasticsearch-2.1.0.jar embeds too much jars

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-elasticsearch-backend-listener#11]
Hello,
I noticed that you use maven shade to build your plugin and provide a fat jar.

But I think it goes too far:
- HC Sync/Async components should not be embedded as they would conflict with embedded ones in JMeter
- Commons codec neither
- com/sun/jna
- log4j could conflict with other from eco system
- jackson also
- joda

Maybe shade plugin should be tuned to:
- minimizeJar
- Exclude some unused deps
- Relocate certain jars

**Comment by delirius325** [comment]
Good point, I'll refactor the pom file to minimize the amount of jars that are packaged within the jar of the plugin itself.

**Comment by pmouawad** [comment]
That’s what we call a cure d’amaigrissement !
28 mb => 9k !

**Comment by delirius325** [comment]
Indeed! It's pretty brutal haha

**Comment by pmouawad** [comment]
Maybe it was a bit too aggressive:

`jar -tvf jmeter.backendlistener.elasticsearch-2.1.1.jar 
     0 Thu Jan 18 12:48:32 CET 2018 META-INF/
   133 Thu Jan 18 12:48:30 CET 2018 META-INF/MANIFEST.MF
     0 Thu Jan 18 12:48:26 CET 2018 net/
     0 Thu Jan 18 12:48:26 CET 2018 net/delirius/
     0 Thu Jan 18 12:48:26 CET 2018 net/delirius/jmeter/
     0 Thu Jan 18 12:48:26 CET 2018 net/delirius/jmeter/backendlistener/
     0 Thu Jan 18 12:48:26 CET 2018 net/delirius/jmeter/backendlistener/elasticsearch/
 12333 Thu Jan 18 12:48:26 CET 2018 net/delirius/jmeter/backendlistener/elasticsearch/ElasticsearchBackend.class
     0 Thu Jan 18 12:48:32 CET 2018 META-INF/maven/
     0 Thu Jan 18 12:48:32 CET 2018 META-INF/maven/net.delirius/
     0 Thu Jan 18 12:48:32 CET 2018 META-INF/maven/net.delirius/jmeter.backendlistener.elasticsearch/
  6445 Thu Jan 18 12:48:14 CET 2018 META-INF/maven/net.delirius/jmeter.backendlistener.elasticsearch/pom.xml
   138 Thu Jan 18 12:48:32 CET 2018 META-INF/maven/net.delirius/jmeter.backendlistener.elasticsearch/pom.properties`

It looks like important dependencies are now missing.
Also I think you should drop this from pom.xml:

`<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>net.delirius.jmeter.backendlistener.elasticsearch.ElasticsearchBackend</mainClass>
</transformer>`

**Comment by delirius325** [comment]
Indeed, might have been a little aggressive. Although, it seemed to be working when I tested on a fresh installation of JMeter. It might have been possible Java was loading cached dependencies somehow.

**Comment by pmouawad** [comment]
I tend to think you may have 2 versions of plugins (old and slim one). Java does not cache dependencies. 
Did you make a test with this PR ? does it work ?
For information , I commented on your jmeter-plugins PR to tell them not to merge it.
Thanks for your work on this.

**Comment by delirius325** [comment]
Indeed this PR works  👍 . Also, I saw your comment on the jmeter-plugins PR, thanks for that! I'll make another one with the JAR resulting from this PR.
