### ISSUE TITLE
behavior when working in Jmeter server

### ISSUE THREAD

**Issue by edubrusch** [delirius325/jmeter-elasticsearch-backend-listener#111]
Hello,

I'm using the result sender in a Jmeter server-client setup. Currently I observed the elasticsearch results are being sent only in the end of the test. In long runs this causes Java to use all memory. So I'd like to test the behavior of it sending metrics as soon as available or in batches. I tried to change the property `mode=Standard` in _jmeter.properties_, but this doesn't seem to have effect. 
Could you please help me?

I'm using jmeter version 5.4.1 with java 1.8 inside a Docker container (alpine).

Thank you for your time and attention. Have a good day.

**Comment by delirius325** [comment]
Yeah JMeter native server-client setup isn't necessarily well supported by the plugin. There are no plans to work on the issue, you're welcome to tackle it though 😄 !
