### ISSUE TITLE
Installing or upgrading plugin via JMeter loops

### ISSUE THREAD

**Issue by softwareconsult** [delirius325/jmeter-elasticsearch-backend-listener#15]
When installing or updating the plugin via JMeter it continuously shows upgrade available.

If we upgrade to 2.2.0 and restart JMeter we are again told to uninstall 2.1.1 and install 2.2.0

![image](https://user-images.githubusercontent.com/18668119/35970320-da6301a4-0cc1-11e8-8b86-ae911527c0c4.png)

**Comment by delirius325** [comment]
Hi,

This is my fault, I forgot to change the downloadUrl on JMeter-Plugins when I made a pull request yesterday.. Just waiting for this pull-request to be merged and the problem will be solved. For now, just installing manually should solve the issue.

https://github.com/undera/jmeter-plugins/pull/227

Thanks,

**Comment by delirius325** [comment]
@softwareconsult Should be fixed now, can you confirm? Thanks.

**Comment by softwareconsult** [comment]
Still the same for me sorry

**Comment by softwareconsult** [comment]
Tried upgrade and also deleting from lib\ext and install. Both result in 2.1.1 file appearing.

**Comment by softwareconsult** [comment]
Just tried again now, it works :) thanks
