### ISSUE TITLE
Empty "es.sample.filter" does not send any sample

### ISSUE THREAD

**Issue by ncasaux** [delirius325/jmeter-elasticsearch-backend-listener#16]
Hello,

It seems that if I don't specity any value in the field "es.sample.filter" of the listener, it does not send any sample. As per the documentation, I was expected that all the samples would be sent as per the documentation.

Tested with JMeter 4.0, ElasticSearch 6.2.1, and 2.2.1 of this plugin.

Regards,
Nicolas

**Comment by delirius325** [comment]
Hi Nicolas,

I'll make sure to check this out today! In the meantime, you can manually rollback to a previous version (2.2.0 should do the trick).

Thanks a lot,

**Comment by ncasaux** [comment]
I confirm that I don't have this issue with version 2.2.0

**Comment by delirius325** [comment]
Issue is fixed in 2.2.2 Created pull request https://github.com/undera/jmeter-plugins/pull/229

For now you can manually update to 2.2.2 by downloading the JAR file in the releases.
Thanks for posting the issue :) !

**Comment by ncasaux** [comment]
I confirm it's fixed in 2.2.2.
You're most welcome, thank you for your plug-in! :)
