### ISSUE TITLE
Plugin doesn't appear in the "Installed" list

### ISSUE THREAD

**Issue by ncasaux** [delirius325/jmeter-elasticsearch-backend-listener#17]
Hello,

The plugin is always in the "Available" list, even when it's already installed.
![image](https://user-images.githubusercontent.com/16475875/36322730-b2d14888-134e-11e8-842e-dc8f5bab1097.png)

Is it a kind of bug of the plugin ?
I'm using JMeter 4.0 with JMeter plugins manager 0.19

**Comment by delirius325** [comment]
Hi,

It seems to be a problem when we install the plugin manually over installing via the Plugins Manager. Not sure if it's related to the plugin itself or the Plugins Manager. I'd have to see with https://github.com/undera/ .

For now though, the pull request for 2.2.2 has been merged, so I suggest you just delete the plugin from the lib/ext folder and install it with the Plugins Manager. Can you come back to me on that?

Thanks a lot,

**Comment by ncasaux** [comment]
Hi,

I just:
1) removed the jmeter.backendlistener.elasticsearch-2.2.2.jar from my lib/ext
2) installed the plugin via the plugin manager
3) restarted JMeter

The plugin still appears as "Available"

**Comment by delirius325** [comment]
Hi, 

Thanks for confirming. I will try to see with the creators of the Plugins Manager, it might be something I'm missing in the configuration over there.

Thanks,

**Comment by pmouawad** [comment]
I confirm the issue.
But I would say it looks more like a JMeter-Plugins Manager bug.

**Comment by delirius325** [comment]
Fixed at the same time as https://github.com/delirius325/jmeter-elasticsearch-backend-listener/issues/18#event-1489895133
