### ISSUE TITLE
Make Plugin-Manager show Maven artifact

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-elasticsearch-backend-listener#18]
Hello,
You published your plugin to Maven recently, which is great.

But in order to make those artifacts visible at jmeter-plugin manager and jmeter-plugins website like this:

<img width="1143" alt="screen shot 2018-02-22 at 22 57 58" src="https://user-images.githubusercontent.com/3127467/36566532-0f57625c-1824-11e8-8928-50fefe08287c.png">

 you should modify your descriptor so that it uses maven artifact instead of github one:

https://search.maven.org/remotecontent?filepath=io/github/delirius325/jmeter.backendlistener.elasticsearch/2.2.2/jmeter.backendlistener.elasticsearch-2.2.2.jar

Regards
Philippe M.

**Comment by pmouawad** [comment]
See:

* https://github.com/undera/jmeter-plugins/pull/234

I would advise you also to add a screenshot on your website and reference it in screenshotUrl.

Une image vaut un long discours :-)

**Comment by delirius325** [comment]
PR Created : https://github.com/undera/jmeter-plugins/pull/235

Tu as bien raison ;) - Thanks for the suggestion!

Pretty sure I fixed https://github.com/delirius325/jmeter-elasticsearch-backend-listener/issues/17 at the same time. The attribute "markerClass" was still pointing to the old package name.

Waiting for PR to be closed to confirm.
