### ISSUE TITLE
Detailed Mode 

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-elasticsearch-backend-listener#19]
Hello,
I think a nice feature of your plugin would be a Detailed mode that would send every elements of a Sampler:

- Request Header+Body
- Response Header+Body

There should be an option to send Successful or Erroneous requests/responses.

During scripting, one would enable ERROR + SUCCESS sending to be able to search using Elastic Search power

During Load Testing, one would only enable ERROR  sending to be able to investigate when errors occur.

What do you think ?
Regards

**Comment by delirius325** [comment]
I think that's a very good idea and it's extremely easy to implement :) !

I will get to it ASAP!

Thanks again for the nice suggestion Philippe!

**Comment by delirius325** [comment]
Added debug and info mode in new version 

https://github.com/delirius325/jmeter-elasticsearch-backend-listener/releases/tag/2.2.3

Would you happen to have any suggestions to the way the functionnality works or should I push to jmeter-plugins and Maven as well?

**Comment by pmouawad** [comment]
Hello Anthony,
Great ! 

I 'll have a closer look in the upcoming days, but for now my suggestions:
- I would use isSuccessful instead of isResponseCodeOK
- Why did you remove sending assertion results ?
- Document the new feature by upgrading screenshot at minimum :-) . Non documented feature does not exist :-)
- For the plugin and to show how great it is, you should propose a template dashboard for detailed and non detailed mode. 

Regards
Philippe M.
@philmdot

**Comment by delirius325** [comment]
Hey Philippe,

- After thinking about it, not really sure why I removed assertion results.. I'll just add it back
- I'll make sure to use isSuccessful instead of isResponseCodeOK
- When I mark the version as release I'll document the new feature :-)
- Great idea, I'll make a template dashboard for both modes. I'll even make one for build comparing when using Jenkins for automated performance testing.

Cheers,
Anthony G.

**Comment by ncasaux** [comment]
Hello,

The assertion results is the main reason I use this plugin :)

**Comment by delirius325** [comment]
Hi,

Yeah no worries though, the release where I removed the assertion results isn't on Maven or JmeterPlugins. It's only a pre-release on this repo.

It'll be added back into the next pre-release.

Thanks,

**Comment by pmouawad** [comment]
Hello @delirius325 ,
I see you released today a new version but don't see any related commit.
Is this regular ?

Thanks

**Comment by delirius325** [comment]
Hi Philippe,

I can't believe I actually forgot to push my changes... Wow... First thing I do in the morning...

😂

**Comment by pmouawad** [comment]
Thanks for pushing.
Code looks good to me although I am not sure I'll have time to test it soon.

Regards

**Comment by pmouawad** [comment]
IMO, default ES_TEST_MODE should be info which is a good option for Load Testing.
Debug is too verbose and might lead "lazy" user to think JMeter+ES Plugin does not scale :-)

Thanks

**Comment by delirius325** [comment]
Hi Philippe,

Thanks for the feed back! Changed ES_TEST_MODE to info. https://github.com/delirius325/jmeter-elasticsearch-backend-listener/commit/e1e6d7287577ac78cb1c8d75a2aaead454f974a3

Only thing that's missing as of right now is the documentation. I'll get started on that ASAP.

**Comment by delirius325** [comment]
Released version 2.2.3 on GitHub. Will deploy to maven and create PR to jmeter-plugins ASAP.

https://github.com/delirius325/jmeter-elasticsearch-backend-listener/releases/tag/2.2.3

**Comment by pmouawad** [comment]
Thanks.
The documentation is in wiki ? thanks

**Comment by delirius325** [comment]
@pmouawad Yes is it in the Wiki, still a work in progress though!
