### ISSUE TITLE
You should add tags / Labels to your repository

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-elasticsearch-backend-listener#21]
Hello,

IMO, in order for your github repository to be more well known, you should add label that appear on top (as for jmeter repository for example):

- jmeter
- elasticsearch
- performance
- jmeter-plugin
- reporting

Regards

**Comment by delirius325** [comment]
Hi @pmouawad,

I already had a few of these topics added to the repository but here is the exhaustive list:

- jmeter
- plugin
- jmeter-plugin
- elasticsearch
- kibana
- java
- backend-listener
- backend
- listener
- jmeter-plugins
- ci
- cd
- continuous-integration
- continous-delivery

--- Newly added ---

- reporting
- performance
- performance-analysis
- performance-testing
- grafana
- elasticsearch-engine

Any more ideas?
Thanks you,

**Comment by pmouawad** [comment]
My mistake , I was kind of bling, I didn't see them all.
