### ISSUE TITLE
Sample filter for error mode is not working

### ISSUE THREAD

**Issue by hanaleung** [delirius325/jmeter-elasticsearch-backend-listener#23]
I think the **es.sample.filter** might be broken for error mode because in this line of code

`validSample = (context.getParameter(ES_TEST_MODE).trim().equals("error") && sr.isSuccessful()) ? false : true;`

it is not checking itself whether it has determined itself to be a validSample already from the previous filter check. So if validSample was determined to be _false_ from the filter check, it switches back to _true_ from this statement

**Comment by delirius325** [comment]
Hi @hanaleung,

My mistake, I'll throw out a fix right now. You'll just have to download the JAR via the GitHub release page.

Thanks :)

**Comment by delirius325** [comment]
Hello again @hanaleung,

I pushed a new release, flagged as pre-release. Please test this JAR:

https://github.com/delirius325/jmeter-elasticsearch-backend-listener/releases/download/2.3.1/jmeter.backendlistener.elasticsearch-2.3.1.jar

Don't forget to remove the 2.3.0 version in your lib/ext folder.

Thanks,
:)

**Comment by hanaleung** [comment]
Thanks again for the quick response!

I've just tried it and it works great :)

**Comment by delirius325** [comment]
Glad it's working! Will publish 2.3.1 as an official version as soon as I have access to a computer.

Thanks for reporting the bug :) !
