### ISSUE TITLE
key value support

### ISSUE THREAD

**Issue by ncasaux** [delirius325/jmeter-elasticsearch-backend-listener#24]
Hello!

Would it be possible to log some additional fields when the request is sent to the ElasticSearch back-end ? Typically, it could be interesting to be able to log some extra fields, like some jmeter properties and/or variables . Some key value pair could maybe be used to achieve this.

**Comment by delirius325** [comment]
Hi @ncasaux ,

This could be a good idea! I'd have to see about the implementation though. The key value pair is probably the best idea, although it's a tricky thing to implement in the UI. Here's the way I see it right now (but I find it could get very messy) :  

es.custom.fields: "key1:value1;key2:value2"

Any ideas?
Thanks :) !

**Comment by ncasaux** [comment]
Hello,

For the properties and variables, maybe we could have an option like "include variables yes/no" and "include properties yes/no" ?

For the specific fields, maybe we could have one row for each key:value pair ? Like:
es.customField.[[myCustomFieldName]]:myCustomFieldValue
Examples:
es.customField.testContext:hardcodedTestContextValue
es.customField.testContext:${some variable or properties}

I hope it's understandable ! :)

**Comment by delirius325** [comment]
Hi,

Very understandable and I do like the idea! I'll try to work something out and I'll let you test it afterwards. This way you'll be able to provide feedback on the way it works, code, and bugs (if found).

This new snapshot should be out in a week or two. 

Thanks,

**Comment by delirius325** [comment]
Released the possibility of adding specific variables in 2.3.2. It's very easy to do. All you have to do is add a field in the backend listener and name it whatever you want it to be, same for the value. As for adding **all** variables, it will be added in 2.3.3 :) !

I pushed 2.3.2 to Maven, also pushed it as a release on this repo. Will merge it to JMeter-Plugins once it's successfully uploaded to Maven's central repository.

Thanks,
