### ISSUE TITLE
Sample in error are not sent to ElasticSearch

### ISSUE THREAD

**Issue by ncasaux-auchan** [delirius325/jmeter-elasticsearch-backend-listener#25]
Hello!

It seems that when a sample fails, the sample results are never sent to ElasticSearch. I tried with the "info" mode and the "debug" mode. 
I used some JMS Publisher samples for my tests. The successfull ones are inserted in ES, but not the others (when I used an incorrect connection for example).

**Comment by ncasaux** [comment]
Issue opened with a wrong account, it can be deleted totally.
