### ISSUE TITLE
passing number parameter to ElasticSearch

### ISSUE THREAD

**Issue by Lemmy321** [delirius325/jmeter-elasticsearch-backend-listener#32]
Hi,

I'm trying to pass a parameter "FileSize" containing a number to Elastic Search. When seeing it in Kibana it's a text field. Any idea how this could be changed to number?

Thanks,
Stefan

**Comment by delirius325** [comment]
Hi @Lemmy321,

By default the plugin will send the parameter as text, as you've seen. I'll have to look into changing that. In the meantime though, you would probably be able to change the type of the field by making a REST call to the ElasticSearch API. See https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html for more information.

Thanks,
