### ISSUE TITLE
basic auth scheme failure

### ISSUE THREAD

**Issue by maxisam** [delirius325/jmeter-elasticsearch-backend-listener#33]
Our ELK setup is like using a reverse proxy to handle all in coming traffic to ElasticSearch endpoint.

And it requires a basic authentication 

The request from logger for RestClient is like `http://username:password@192.168.56.120/elasticsearch:80`

and it shows an error like 

```java
java.net.UnknownHostException: username:password@192.168.56.120/elasticsearch: invalid IPv6 address
```
Thanks!

**Comment by delirius325** [comment]
Hey @maxisam,

Just to let you know I'll look into this on Monday.

Thanks 😄

**Comment by delirius325** [comment]
Sorry I couldn't be of much help.. Best of luck!
