### ISSUE TITLE
Regarding filters with a ; separated list

### ISSUE THREAD

**Issue by hanaleung** [delirius325/jmeter-elasticsearch-backend-listener#37]
Hello,

Sorry to be a bother again, 
This is more of a question as to if i'm using the multiple filters correctly, 

It's highlighted that if i want to use multiple filters, i should separate them with a ; like so:

> filter1;filter2;filter3

I'm not sure if my expectation is correct, If i put es.sample.filter = "R_/;A_/", should that be picking up both requests that contains R_/ and A_/, is this an OR or an AND is my question?

I'm looking for the functionality to act more as an OR since i'm looking to implement some distinction between labels in jmeter but still allow elasticsearch to log messages with labels containing either R_ and A_ but it doesn't seem to work that way.

I used "R_/;A_/" as my filter and it seems to ignore all my samplers with labels R_, when i remove the second filter, it works as intended :)

**Comment by delirius325** [comment]
Hi @hanaleung ,

First of all, thanks for the feedback - it is greatly appreciated! As for the filter functionality, it is suppose to act as an "OR" condition.

I will review the method again, might of missed something. Hopefully I can fix it once and for all 😆 !

Thanks again,

**Comment by hanaleung** [comment]
Thanks very much!

Dumb question but if i wanted to workaround to get this behavior in the meantime by just using two listeners, would that actually work? One set to filter on R_/ and one set to filter on A_/ or will that cause more issues.

**Comment by delirius325** [comment]
Hey there @hanaleung,

Finally fixed it - coming to PluginsManager and Maven but for the meantime : https://github.com/delirius325/jmeter-elasticsearch-backend-listener/releases/tag/2.5.4

Thanks a lot 😄 !
