### ISSUE TITLE
using regex in filter?

### ISSUE THREAD

**Issue by triportland** [delirius325/jmeter-elasticsearch-backend-listener#38]
Is there the ability to use regex in the filter field?  It would be handy if there is, especially in the case where we want to omit sampleLabels that we don't want to send to ES.

Thanks

**Comment by triportland** [comment]
Awesome!  Thank you @delirius325 
Looking forward to using it in the next version.

**Comment by delirius325** [comment]
Hi @triportland ,

Version 2.6.0 has been released and makes use of the possibility of adding regular expressions to the filter feature. Currently, the JAR is downloadable from the "Release" section on this repository. 

Cheers!

**Comment by triportland** [comment]
Hi @delirius325
Is there any trick to using regex in the filter field?
I tried with this regex expression: (^[^000].*)
and my sample label paterns are:
- Normal Sample Label
-000dontsendthissample
The goal is to filter out anything that starts with 000, but so far it's not doing the trick.

Thanks

**Comment by triportland** [comment]
Tested out the new 2.6.0 version and regex works great.
Thanks @delirius325

**Comment by delirius325** [comment]
Glad to hear this ! @triportland
