### ISSUE TITLE
Missing sentBytes

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-elasticsearch-backend-listener#4]
Since JMeter 3.1, there is a new interesting metric sent_bytes that is interesting to send.
So you could use:

`        jsonObject.put("BodySize", sr.getBodySizeAsLong());
        jsonObject.put("Bytes", sr.getBytesAsLong());
        jsonObject.put("SentBytes", sr.getSentBytes());
`

**Comment by delirius325** [comment]
Will definitely be added into the next version of the plugin, thanks!
