### ISSUE TITLE
Required Total Summary & Total Requests Graph 

### ISSUE THREAD

**Issue by gmaheshsri** [delirius325/jmeter-elasticsearch-backend-listener#47]
Hi All,

In our project we are expecting the graph similar to influxdb & requesting to please help me out by sharing your valuable suggestions.

Regards,
Mahesh
![Influxdb](https://user-images.githubusercontent.com/38001748/57146581-4db19c00-6de3-11e9-8c4d-fa8eae818851.png)

**Comment by gmaheshsri** [comment]
Hi All,

Any suggestions or can i expect any updated json dashboard to integrate with Elasticsearch, for reflecting above details included with existing code.

Thanks,
Mahesh

**Comment by delirius325** [comment]
Hi @gmaheshsri ,

These should be fairly simple to implement in Grafana. Sadly I don't really have the time to generate the dashboard for you. But as far as I'm concerned, these are just 2 gauges which use the `ErrorCount` parameter that the plugin sends to ElasticSearch. If it's at `1` then it means the sampler resulted in an error. 

Then you can just aggregate and sum the amount of samplers you have within the defined time range and you should be able to calculate the percentage of errors.

The two other panels are simply two panels which show the amount of requests failed (so sum of `ErrorCount`) and the total amount of requests.

From there you should be able to fiddle around to recreate these 4 panels.

Thanks,

**Comment by gmaheshsri** [comment]
Thanks Delirius for your reposne & basically I am not a developer to implement above changes, can you please help us how to write a query in elastic search & how to fetch the table names. Based on that will take forward.

Thanks.

**Comment by delirius325** [comment]
Using Grafana, you don't need to develop any sort of advanced queries. All you have to do is use the correct datasource and create a new gauge panel referencing the correct index properties. It's pretty much click & generate.

**Comment by gmaheshsri** [comment]
Thanks delirius for the clarification, can you please help me giving
exactly url which will help me to understand. I already did homework from
my end but no luck.
