### ISSUE TITLE
Compare Jenkins builds in Grafana

### ISSUE THREAD

**Issue by debajyotichanda** [delirius325/jmeter-elasticsearch-backend-listener#48]
Thank you very much for providing such a detailed information and it worked great for me. I have a query for the build comparison in Grafana. 

You mentioned :
"Whether you use Grafana or Kibana, you can then compare the builds by splitting the series with the BuildNumber field."

I am able to pass the Jenkins BUILDNUMBER value to Grafana but not able to filter the results by builds. How do you suggest to compare the builds by splitting the series with the BuildNumber field. Can you please add an example. 

Much appreciate your contribution.

**Comment by delirius325** [comment]
Hi @debajyotichanda ,

I might have to update the README, I have been able to split the series on Kibana but I don't think I've been able to do it on Grafana just yet. In Kibana, literally all you need to do is add a sub-aggregation by terms on the field "BuildNumber".

This way you'll be able to show in descending or ascending order the last X builds and compare their response time.

Hopes this help,
