### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by daniew01** [delirius325/jmeter-elasticsearch-backend-listener#49]
Hi

I have the 2.6.1 version of the jar file and got JMeter to send to ElasticSearch Rest port. However when the ES port is behind https it is not working as expected. I added the new server IP as well as username/password and ran the same jmeter test. The Jmeter console log states "ElasticSearchMetricSender: Index already exists!" and then later in the log it states:
"2019-05-20 11:41:32,967 ERROR i.g.d.j.b.e.ElasticSearchMetricSender: Exceptionjava.lang.RuntimeException
2019-05-20 11:41:32,967 ERROR i.g.d.j.b.e.ElasticSearchMetricSender: ElasticSearch Backend Listener was unable to perform request to the ElasticSearch engine. Request reached timeout."

I am not sure if I configured the es.scheme correct nor if I have to pull the self-signed cert into JMeter

I have created a keystore but am not sure where to add this in the config

Regards
DJW

**Comment by delirius325** [comment]
Hi there, 

For me to be able to help I would have to know how you setup the listener. Could you please supply a screenshot or a list of the parameters.

Thanks,

**Comment by daniew01** [comment]
Hi
Changes I made is to:
 - scheme : https
 - host -> ipadress of host
 - port :9300
 - index -> jmeter
 - username: username of account that has access
 - password: password for the user

If I use an Elasticsearch server without https then index gets created and
I can see the entries in the discovery tab. The problem is when I connect
to an Elasticsearch server configured with security

[image: Jmeter_BackendListerner.png]




*Kind RegardsDanie Weideman*
082 650 0768 (M)

**Comment by delirius325** [comment]
Are you sure port is 9300? 9300 is usually the transport protocol port. Try 9200

**Comment by daniew01** [comment]
Hi
Apologies finger trouble port is 9200.

Sorry about this, my mistake

Djw

**Comment by delirius325** [comment]
No worries, is this issue solved? If so, just hit the close issue button. Thanks!

**Comment by daniew01** [comment]
Hi
Issue not closed.

How do u handle the https protocol and certificate? I think this is the
blocking factor

I think there is a switch "-k" or "-f" that can be passed to port 9200 that
will ignore certifcates. How can I use this switch in the configuration?

Are there any logs I can send you.


Kind regards
Djw

**Comment by delirius325** [comment]
Hi @daniew01,

Ignoring certificates is generally a bad idea (although there are some cases when it's needed). Have you tried supplying JMeter with the keystore via the KeyStore Manager? If not, maybe try that at first. Otherwise we'll look into a concrete solution for this.

Thanks,

**Comment by daniew01** [comment]
Hi
I have added the Keystone and certificate but still having the same issue.

Kind Regards
Djw

**Comment by daniew01** [comment]
Hi
Any updates ?
The http connection works fine

**Comment by delirius325** [comment]
@daniew01 You should be able to solve this issue by using the new features of 2.6.5 😄 !

Cheers,

**Comment by JhanaHoracio** [comment]
Hi guys, 

how can I solve this problem in the version 5.6? What was the solution ?
