### ISSUE TITLE
New Features/Fields request

### ISSUE THREAD

**Issue by nareshnakka** [delirius325/jmeter-elasticsearch-backend-listener#53]
TestStartTime field is changing for every field. It should be constant across the test. Can you please fix it.

Adding to it, Can you please add below fields also to be logged to elastic. For a performance tester, while creating dashboard it is very useful.

1. TestExecutionIteration
2. TestAppName
3. TestAppBuildNumber/TestAppVersionNumber
4. TestType

**Comment by delirius325** [comment]
Hi @nareshnakka,

I'll be looking into this.

Thanks,

**Comment by delirius325** [comment]
`TestStartTime` that field did not exist. It was `StartTime` which is the Sample Start Time. I'm currently in the midst of releasing a new version and I made the follwing modification:

```
StartTime -> SampleStartTime
EndTime -> SampleEndTime
added TestStartTime
```

As far as the custom fields you mentioned, you can add them yourself as custom parameters in the listener.

Cheers,

**Comment by nareshnakka** [comment]
Does it require any code change in classes?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by delirius325** [comment]
It's just a matter of adding custom parameters in your listener within JMeter. See README for more information.

Thanks
