### ISSUE TITLE
Plugin failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by syampol** [delirius325/jmeter-elasticsearch-backend-listener#55]
Tried plugin with Elastic 5.4 and 7.1.
Both are failed on Ubuntu 16.04 with
`2019-06-19 12:35:25,298 INFO o.a.j.v.b.BackendListener: Backend Listener Elasticsearch: Starting worker with class: class io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient and queue capacity: 5000
2019-06-19 12:35:25,303 INFO o.a.j.v.b.BackendListener: Backend Listener Elasticsearch: Started  worker with class: class io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient
2019-06-19 12:35:25,757 INFO i.g.d.j.b.e.ElasticSearchMetricSender: Index already exists!
2019-06-19 12:35:35,820 ERROR i.g.d.j.b.e.ElasticSearchMetricSender: Exceptionjava.lang.RuntimeException
2019-06-19 12:35:35,820 ERROR i.g.d.j.b.e.ElasticSearchMetricSender: ElasticSearch Backend Listener was unable to perform request to the ElasticSearch engine. Request reached timeout.`

Same plan works fine from Windows machine (full copy of Jmeter's lib directory).
Error points to timeout occurred, however there is shouldn't be any timeout there as host is definitely reachable.

One more weird item is this:
`2019-06-19 12:35:25,757 INFO i.g.d.j.b.e.ElasticSearchMetricSender: Index already exists!`
Although index is unique per each run and doesn't exist on Elastic side. Elastic's show indexes doesn't show such index either.

**Comment by syampol** [comment]
p.s. we are using several custom plugins, so there are lots of other dependencies (placed to lib/ext).
but again it doesn't work on Ubuntu and does work on Win

**Comment by delirius325** [comment]
Hey @syampo,

May I see your plugin configuration as well as your JMeter console (not log, the console - meaning the terminal where you started it).

Thanks,

**Comment by syampol** [comment]
hi
it's started within a container.
stderr - is empty
stdout - nothing special
`Creating summariser <summary>
Created the tree successfully using /apps/injector/projects/6111/testplan/23_IMS/Jmeter_LOAD_test.jmx
Starting the test @ Wed Jun 19 12:51:10 UTC 2019 (1560948670972)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
Startup script running
Startup script completed
Httpd started on port: 9000
Sessiond started on port: 9001
`
jmeter.log - attached
bl_cfg - attached
[jmeter.zip](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/files/3306275/jmeter.zip)
![bl_cfg](https://user-images.githubusercontent.com/51999318/59769281-7a941280-92ae-11e9-8863-d9abd835d7f9.png)

**Comment by syampol** [comment]
`e.printStackTrace();`
before
`logger.error("ElasticSearch Backend Listener was unable to perform request to the ElasticSearch engine. Request reached timeout.");`
results in:

> java.lang.RuntimeException
>         at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:951)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:227)
>         at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticSearchMetricSender.sendRequest(ElasticSearchMetricSender.java:104)
>         at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.handleSampleResults(ElasticsearchBackendClient.java:148)
>         at org.apache.jmeter.visualizers.backend.BackendListener.sendToListener(BackendListener.java:267)
>         at org.apache.jmeter.visualizers.backend.BackendListener$Worker.run(BackendListener.java:239)
> Caused by: java.lang.IllegalStateException
>         at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient$1.onFailure(ElasticsearchBackendClient.java:101)
>         at org.elasticsearch.client.RestClient.onFailure(RestClient.java:728)
>         at org.elasticsearch.client.RestClient.access$400(RestClient.java:98)
>         at org.elasticsearch.client.RestClient$1.failed(RestClient.java:560)
>         at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
>         at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
>         at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
>         at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:348)
>         at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
>         at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:392)
>         at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
>         at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:291)
>         at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
>         at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
>         at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
>         at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:529)
>         at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:514)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:226)
>         ... 4 more

**Comment by syampol** [comment]
hi,
really sorry for wasting your time ((
issue was because of missing 'schema' parameter.
worked on Win, as was running through UI and parameter set as default.
on Ubuntu running in non-GUI mode and was an issue with test plan creation.

please close if think this not an issue, or set as enhancement and add validation for mandatory parameters resulting in meaningful error message.
