### ISSUE TITLE
Feature request: Please add MAX allowed request/response size configurable param

### ISSUE THREAD

**Issue by syampol** [delirius325/jmeter-elasticsearch-backend-listener#56]
It would be nice to have a possibility to set MAX allowed request/response body size to be written to Elastic.
Sometimes responses might be really huge and not really needed for debugging. So it would be great to have an option to not send redundant data to Elastic. (Especially taken into account Elastic does have a limitation 

> index has exceeded [1000000] - maximum allowed to be analyzed for highlighting
)

**Comment by delirius325** [comment]
Hi there @syampol ,

As per the README, there are 4 possible test modes;

> * **debug** : Send request/response information of all samplers (headers, body, etc.)
> * **info** : Sends all samplers to the ElasticSearch engine, but only sends the headers, body info for the failed samplers.
> * **quiet** : Only sends the response time, bytes, and other metrics
> * **error** : Only sends the failing samplers to the ElasticSearch engine (Along with their headers and body information).

I believe that `quiet` or `info` would be the required mode for your use-case. 
Thanks,

**Comment by syampol** [comment]
Actually no.
What I was looking for is debug mode with an ability to shrink large responses.

however i wouldn't insist in reopening as this is not smth critical

**Comment by delirius325** [comment]
@syampol Ahh okay, I understand!

Although I believe as a best-practice, debugging should be done through the JMeter GUI with a `View Results Tree` element. Sending your sample results to ES should only be done when executing your tests in preparation for your application's production release.

I'd also suggest/recommend using the `info` when not debugging your script. That way, only the failed samples (which there technically shouldn't be a whole lot of) would have their request/response body sent to ES.

Sorry I couldn't be of much help..
Regards,
