### ISSUE TITLE
No samples sent to ES using SSL

### ISSUE THREAD

**Issue by burtoni** [delirius325/jmeter-elasticsearch-backend-listener#63]
I'm using ES and Kibana 5.5.3 with the following configuration in the backend listener:
```
es.scheme = https
es.host = myserver
es.port = 443
es.index = jmeter-jtldata-2019.08.08/samples
es.timestamp = yyyy-MM-dd'T'HH:mm:ss.SSS
es.test.mode = quiet
```

This works on my local Dockerized ELK cluster when es.scheme = http and es.port = 9200, however the above configuration appears to fail to send messages to the specified index.

There are no errors/warnings in jmeter.log or the console.

I can confirm messages are sent to the index correctly when sending a dummy JSON message via CURL, so it doesn't appear to be a connectivity issue:
```
curl -H 'Content-Type:application/json' -XPOST 'https://myserver:443/jmeter-jtl-2019.08.06/samples' -d '{ "timestamp": "2019-08-06T04:36:03.100Z", "rc": "200", "rm" : "OK" }'
{"_index":"jmeter-jtl-2019.08.06","_type":"samples","_id":"AWxvT8K_jc_DxjOFCmM9","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"created":true}
```

**Comment by delirius325** [comment]
Hi,

Have you tried setting up the SSL parameters in the ElasticSearch listener? If you don't seem them, please update to the latest version.

The parameters are;
``
`
es.ssl.truststore.path
es.ssl.truststore.pw
es.ssl.keystore.path
es.ssl.keystore.pw
```

Thanks,

**Comment by delirius325** [comment]
Closed for inactivity.
