### ISSUE TITLE
Documentation link to Sample Dashboard doesn't correct

### ISSUE THREAD

**Issue by leonsery** [delirius325/jmeter-elasticsearch-backend-listener#64]
There is a link (https://github.com/delirius325/jmeter-elasticsearch-backend-listener/wiki/Grafana---JMeter-Generic-Dashboard) to Generic Dashboard json, but it is differ from one shown as a picture (much better one!)
Please update the dashboard json!

**Comment by delirius325** [comment]
Fixed #64 - Updated main dashboard and added error+drilldown dashboards as well.
