### ISSUE TITLE
Thread and transaction stats

### ISSUE THREAD

**Issue by Charek** [delirius325/jmeter-elasticsearch-backend-listener#70]
Hi,
What part of the plugin code can send metrics for jmeter thread and transaction controller counts? It seems the plugin only sends http sampler results.
The original graphite backend listener did this so the elastic plugin could be modified to do the same?  I would like to graph throughput for transaction controllers of http samplers, their ok and ko counts along with how it changes with jmeter thread load.
Thanks

**Comment by Charek** [comment]
Ignore the part about the transaction controller counts. The plugin does provide this. For active thread count, doesn't seem it would be in a sampler but I suppose we could count the distinct threadnames for a given time period.

**Comment by delirius325** [comment]
Sorry for the very late response, I assume you've figured out a way to do this. But yes, back when I was using the plugin in my day-to-day tasks, that's how I would do it. Count the distinct thread names to get the amount of threads.
