### ISSUE TITLE
Upgrade ES Client to 7.x?

### ISSUE THREAD

**Issue by triportland** [delirius325/jmeter-elasticsearch-backend-listener#71]
This is more of an enhancement request.  Just wonder if you have any plan to upgrade the Elasticsearch client from 6.4 to 7.3?  There are methods in 6.4 that are deprecated and not supported in 7.x version (ie: index call doesn't support the type field anymore)

Reason for this is that I'm writing a small library to handle SSE data inside a stream, using ES HighLevel Rest Client, my ES server is on 7.x and so I need my client to be on 7.x also.  When I used both my library and this plugin in jMeter, I ran into the incompatibility issue.  I'd love to use both.
Thanks

**Comment by delirius325** [comment]
Hi @triportland ,

Have you upgraded the plugin to its latest version? We added support for ES 7.X a while back 😄 !

**Comment by triportland** [comment]
I understand and have been using it with ES 7.x.  The issue is if I'm in a situation where I have my own ES client with 7.3 version and it is incompatible with the 6.4 version.  I guess I can rewrite my code to use the LowLevel Rest Client just like you or just simply use your classes (with some modification since the data I'm capturing is not jMeter Sampler format). :)

**Comment by delirius325** [comment]
That would be the way to😊
