### ISSUE TITLE
Skip SSL Verification Mode

### ISSUE THREAD

**Issue by jensdon** [delirius325/jmeter-elasticsearch-backend-listener#73]
In the connection between Filebeat and ES im using the `setting: ssl.verification_mode: "none"`
How can I skip the SSL verification in your plugin? My Elastic instance is accessible via https but there is no right certificate available.

**Comment by delirius325** [comment]
Hi @jensdon ,

Sorry for the very late response, I haven't been maintaining this repository as well as I should have lately. Have you been able to fix your issue?

Thanks,
