### ISSUE TITLE
Unable to post data from Jmeter to Elasticsearch using backend listener

### ISSUE THREAD

**Issue by sg86-sourav** [delirius325/jmeter-elasticsearch-backend-listener#74]
Hi,

I am facing an issue for long time while trying to post data from Jmeter to Elasticsearch using Backend Listener. The Elasticsearch [version : 6+] is installed on remote server and accessible through HTTPS connection. We have created the index in the Elasticsearch using console and the mapping is showing as below and this is the default mapping set by project team.

index : test1234

{
  "mapping": {
    "_doc": {
      "dynamic": true
    }
  }
}

While executing the test, Jmeter backend listener is using "https://<HOST>:443/test1234/SampleResult/_bulk" URL to post data into elasticsearch and the request is getting timed out. I believe the URL is not correct and that is why the request is getting timed out.

So, how we can update the POST url for pushing the data into elasticsearch.

Please let me know if any further information is required.

**Comment by delirius325** [comment]
Hi,

Please provide me with a screenshot of your backend listener configuration.

Thanks,

**Comment by sg86-sourav** [comment]
Hi,

Please find below the backend listener snapshoot-

![image](https://user-images.githubusercontent.com/61148854/74657525-b3afba00-5190-11ea-860c-dfe1e2be5d8b.png)

**Comment by delirius325** [comment]
Mmmh, everything seems to be okay. Is the port you guys are using really `443`? What exactly made you think the URL wasn't right to begin with? 

I know several people who use this plugin in their day-to-day operations and have no issues with it. If you look at the code, the URL is formed with the first three (3) parameters;

* `es.scheme`
* `es.host`
* `es.port`

If the URL you see doesn't correspond to what you need, then there must be an error in one of the 3 parameters listed above.

**Comment by delirius325** [comment]
Also, on the same machine you're using for the JMeter GUI, can you open up a browser and ping your elasticsearch instance?

`scheme://host:port` (`https://bla-bla-bla:443`)

**Comment by sg86-sourav** [comment]
Yes, the port is correct as while giving an index in backend listeners which is not present in ElasticSearch, in that case the index is getting created in ES but data is not getting posted.

Also, we can POST the data into ElasticSearch using Postman from the same machine from where I am running JMeter.

While checking the source code for ElasticSearchMetricsSender.java, I can see the following line where it is appending "/SampleResult/" in the URL in case the ES version is less than 7. Can we edit this URL ?

**if(elasticSearchVersionPrefix < 7) {
    		 request = new Request("POST", "/" + this.esIndex + "/SampleResult/_bulk");
 			 actionMetaData = String.format(SEND_BULK_REQUEST, this.esIndex, "SampleResult");
    	}
    	else {
    		 request = new Request("POST", "/" + this.esIndex + "/_bulk");
    		 actionMetaData = String.format(SEND_BULK_REQUEST, this.esIndex);
    	}**

Please find below the response I am getting while hitting the host in the browser

{
  "name" : "es-client-646xxxxxx9b-hqxxxj",
  "cluster_name" : "es-cluster",
  "cluster_uuid" : "78Bpxxxxxxxxfy2tsWMCwxxxx",
  "version" : {
    "number" : "6.7.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "56xxxxx8",
    "build_date" : "2019-xx-xxT09:05:50.290371Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by delirius325** [comment]
The `SampleResult` shouldn't cause any issues in ES version >= 6.X.X. The issue seems to be something else, not the URL. The fact that your requests result in timeouts is quite strange, it's as if your JMeter instance was unable to reach the ES instance. 

Could you supply me with the HTTP request you're doing and the JMeter log as well as the console log (2 different things). 

Try changing your HTTP Sampler so that it sends requests to a well known website, try `google.com` for example. See if these requests go through.

Thanks,

**Comment by debajyotichanda** [comment]
Hi Anthony,

We are using following plugin to send Jmeter metrics to Elasticserach : jmeter.backendlistener.elasticsearch-2.6.9.jar

Getting the following error in JMeter logs: 
java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequest(Lorg/elasticsearch/client/Request;)Lorg/elasticsearch/client/Response;
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticSearchMetricSender.createIndex(ElasticSearchMetricSender.java:95) ~[jmeter.backendlistener.elasticsearch-2.6.9.jar:?]
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.setupTest(ElasticsearchBackendClient.java:139) ~[jmeter.backendlistener.elasticsearch-2.6.9.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:349) ~[ApacheJMeter_components.jar:3.2 r1790748]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:302) ~[ApacheJMeter_components.jar:3.2 r1790748]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:218) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:388) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
2020-02-19 11:03:02,431 ERROR i.g.d.j.b.e.ElasticsearchBackend: ElasticSearch Backend Listener was unable to perform request to the ElasticSearch engine. Request reached timeout.

Our Jmeter version is : 3.2

Please suggest the needful. We are actually trying to use the SSL version of the ELK cluster. The old plugin version 2.2.5 is working just great. 

Please see if you can help. 

Thanks 
DJ

**Comment by delirius325** [comment]
Comment deleted as it was a double of the issue in #75

**Comment by delirius325** [comment]
@sg86-sourav , was the issue solved? If I don't have an answer by 4PM EST I'll close this issue.

**Comment by debajyotichanda** [comment]
Hi Anthony!!
I am facing the same issue. Can you please let me know a workaround. 
Much appreciate.
