### ISSUE TITLE
setMaxRetryTimeoutMillis is deprecated and removed from RestClientBuilder

### ISSUE THREAD

**Issue by sivaram-vu** [delirius325/jmeter-elasticsearch-backend-listener#79]
In ElasticsearchBackendClient, Please remove the usage of setMaxRetryTimeoutMillis as this is deprecated and removed in recent versions.
https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-client/6.7.1/org/elasticsearch/client/RestClientBuilder.html#setMaxRetryTimeoutMillis(int).

**Comment by delirius325** [comment]
Good catch! Mind making a PR for it?

**Comment by delirius325** [comment]
Fixed in 2.6.11
