### ISSUE TITLE
Send extracted data into ElasticSearch using backend listener

### ISSUE THREAD

**Issue by sg86-sourav** [delirius325/jmeter-elasticsearch-backend-listener#81]
Hi Delirius325,

We have a requirement to capture some value (say transaction id) from JSON response and post the value into ElasticSearch. So is it be possible to send captured value into ElasticSearch using backend listener ? If yes, then please share me the steps I have to follow.

**Comment by delirius325** [comment]
Hi @sg86-sourav,

It is possible, please refer to [this](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/blob/0aa6b59425f2bca1254404164f1640c961828bf3/src/main/java/io/github/delirius325/jmeter/backendlistener/elasticsearch/ElasticsearchBackendClient.java#L116-L120)

The request you'll most likely want to use will be the "Request Headers" method.

Thanks,
