### ISSUE TITLE
Could not separate request by injctor slave

### ISSUE THREAD

**Issue by anasoid** [delirius325/jmeter-elasticsearch-backend-listener#88]
i can't see request by injector node, the field InjectorHostname not work and have always the value of master node.

Look like slave send sampleresult to master and master send data to elastic

**Comment by delirius325** [comment]
Hi @anasoid, 

Indeed if you are using the native distributed testing from JMeter, that's just the way it works. The slaves are sending the results back to the master and the master sends everything to ElasticSearch, therefore using its' hostname.

I've always used a different approach to distributed testing in JMeter than the native one, but a workaround for this might be to use JMeter properties to retrieve the hostname and pass it as a header value with your HTTP Samplers. 

Don't forget to enable "es.parse.all.req.headers".

**Comment by anasoid** [comment]
Thanks @delirius325.

I understood  that technically Jmeter don't open any way to have this information (injector node) at Listener Level.

**Comment by delirius325** [comment]
@anasoid Exactly! That's why I suggest doing it at a sampler level :smile: 

That way the data sent back to the master listener is "precomputed". 

Anyways, hope this helped!
